# AUTO-GENERATED FILE, DO NOT EDIT. ALL CHANGES WILL BE LOST!
FLASH_AREA_BOOTLOADER_DEV_ID :=FLASH_DEVICE_INTERNAL_FLASH
FLASH_AREA_BOOTLOADER_START :=0x000000
FLASH_AREA_BOOTLOADER_SIZE :=0x020000
FLASH_AREA_IMG_1_PRIMARY_DEV_ID :=FLASH_DEVICE_INTERNAL_FLASH
FLASH_AREA_IMG_1_PRIMARY_START :=0x020000
FLASH_AREA_IMG_1_PRIMARY_SIZE :=0x0c0000
FLASH_AREA_IMG_1_SECONDARY_DEV_ID :=FLASH_DEVICE_EXTERNAL_FLASH(CY_BOOT_EXTERNAL_DEVICE_INDEX)
FLASH_AREA_IMG_1_SECONDARY_START :=0x1d60000
FLASH_AREA_IMG_1_SECONDARY_SIZE :=0x0c0000
MCUBOOT_IMAGE_NUMBER := 1
MCUBOOT_MAX_IMG_SECTORS := 1536
APP_CORE := CM0P
USE_OVERWRITE := 1
USE_EXTERNAL_FLASH := 1
