#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries
SEARCH_emeeprom=./libs/emeeprom



# The search paths for the included middleware
SEARCH_block-storage=../mtb_shared/block-storage/release-v1.3.2
SEARCH_cat1cm0p=../mtb_shared/cat1cm0p/release-v1.4.0
SEARCH_cmsis=../mtb_shared/cmsis/release-v5.8.0
SEARCH_core-lib=../mtb_shared/core-lib/release-v1.4.1
SEARCH_core-make=../mtb_shared/core-make/release-v3.3.1
SEARCH_emeeprom=./libs/emeeprom
SEARCH_mtb-hal-cat1=../mtb_shared/mtb-hal-cat1/release-v2.5.4
SEARCH_mtb-pdl-cat1=../mtb_shared/mtb-pdl-cat1/release-v3.9.0
SEARCH_recipe-make-cat1a=../mtb_shared/recipe-make-cat1a/release-v2.2.0

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_block-storage)
SEARCH_MTB_MK+=$(SEARCH_cat1cm0p)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_emeeprom)
SEARCH_MTB_MK+=$(SEARCH_mtb-hal-cat1)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat1)
SEARCH_MTB_MK+=$(SEARCH_recipe-make-cat1a)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_BLOCK_STORAGE
COMPONENTS += MW_CAT1CM0P
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_EMEEPROM
COMPONENTS += MW_MTB_HAL_CAT1
COMPONENTS += MW_MTB_PDL_CAT1
COMPONENTS += MW_RECIPE_MAKE_CAT1A


#
# generate make targets for the graphical editors that are specific to this project
#

.PHONY: mtb_help_tools_start mtb_help_tools_end
