/******************************************************************************
* File Name: cycfg_gatt_db.c
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.90.0.2529
*
*******************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
******************************************************************************/

#include "cycfg_gatt_db.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"

/******************************************************************************
* GATT service database definitions
******************************************************************************/
const uint8_t gatt_database[] = 
{
    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (
            HDLS_GATT,
            __UUID_SERVICE_GENERIC_ATTRIBUTE),
        /* Characteristic: Service Changed Indicate that entire GATTDB has been altered*/
        // (handles: 0x0000 - 0xffff)
        CHARACTERISTIC_UUID16(
                HDLC_GATT_SERVICE_CHANGED,
                HDLC_GATT_SERVICE_CHANGED_VALUE,
                __UUID_CHARACTERISTIC_SERVICE_CHANGED,
                GATTDB_CHAR_PROP_INDICATE,
                GATTDB_PERM_NONE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_GATT_SERVICE_CHANGED_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),

    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (
            HDLS_GAP,
            __UUID_SERVICE_GENERIC_ACCESS),     //0x1800
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16_WRITABLE (
                HDLC_GAP_DEVICE_NAME,      //name     
                HDLC_GAP_DEVICE_NAME_VALUE,//name value
                __UUID_CHARACTERISTIC_DEVICE_NAME,//char 0x2A00
                GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_WRITE,//property
                GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ), //permission
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (
                HDLC_GAP_APPEARANCE,
                HDLC_GAP_APPEARANCE_VALUE,
                __UUID_CHARACTERISTIC_APPEARANCE,//char 0x2A01
                GATTDB_CHAR_PROP_READ,//property
                GATTDB_PERM_READABLE),//permission

    // /* Primary Service: Generic Attribute */
    // PRIMARY_SERVICE_UUID16 (
    //         HDLS_GATT,//declaration
    //         __UUID_SERVICE_GENERIC_ATTRIBUTE),  //0x1801

    // /* Primary Service: Battery */
    // PRIMARY_SERVICE_UUID16 (
    //         HDLS_BAS,//declaration
    //         __UUID_SERVICE_BATTERY),            //0x180F
    //     /* Characteristic: Battery Level */
    //     CHARACTERISTIC_UUID16 (
    //             HDLC_BAS_BATTERY_LEVEL,
    //             HDLC_BAS_BATTERY_LEVEL_VALUE,//read data by the handle.
    //             __UUID_CHARACTERISTIC_BATTERY_LEVEL,//uuid
    //             GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
    //             GATTDB_PERM_READABLE),
    //         /* Descriptor: Characteristic Presentation Format */
    //         CHAR_DESCRIPTOR_UUID16 (
    //                 HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT,
    //                 __UUID_DESCRIPTOR_CHARACTERISTIC_PRESENTATION_FORMAT,  //0x2904
    //                 GATTDB_PERM_READABLE),
    //         /* Descriptor: Client Characteristic Configuration */
    //         CHAR_DESCRIPTOR_UUID16_WRITABLE (
    //                 HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,
    //                 __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
    //                 GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),

    /* Primary Service: OTA FW Upgrade Service */
    PRIMARY_SERVICE_UUID128 (
            HDLS_OTA_FW_UPGRADE_SERVICE,
            __UUID_SERVICE_OTA_FW_UPGRADE_SERVICE),
        /* Characteristic: OTA Upgrade Control Point */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_CONTROL_POINT,
                HDLC_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_CONTROL_POINT_VALUE,
                __UUID_CHARACTERISTIC_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_CONTROL_POINT,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_NOTIFY | GATTDB_CHAR_PROP_INDICATE,
                GATTDB_PERM_WRITE_REQ),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_CONTROL_POINT_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
        /* Characteristic: OTA Upgrade Data */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_DATA,
                HDLC_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_DATA_VALUE,
                __UUID_CHARACTERISTIC_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_DATA,
                GATTDB_CHAR_PROP_WRITE,
                GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_RELIABLE_WRITE),

    /* Primary Service: Session Service */
    PRIMARY_SERVICE_UUID128 (
            HDLS_SESSION_SERVICE,
            __UUID_SERVICE_CUSTOM_SESSION_SERVICE),
        /* Characteristic: Device information Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_DEVICE_INFORMATION_CHAR,
                HDLC_SESSION_SERVICE_DEVICE_INFORMATION_VALUE,
                __UUID_CHARACTERISTIC_DEVICE_INFORMATION_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: Device information Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_SESSION_SERVICE_DEVICE_INFORMATION_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Time Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_TIME_CHAR,
                HDLC_SESSION_SERVICE_TIME_VALUE,
                __UUID_CHARACTERISTIC_TIME_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
        /* Characteristic: Battery Power Remaining Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_BATTERY_POWER_REMAINING_CHAR,
                HDLC_SESSION_SERVICE_BATTERY_POWER_REMAINING_VALUE,
                __UUID_CHARACTERISTIC_BATTERY_POWER_REMAINING_CHARACTERISTIC,
                GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_SESSION_SERVICE_BATTERY_POWER_REMAINING_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Device lock Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_DEVICE_LOCK_CHAR,
                HDLC_SESSION_SERVICE_DEVICE_LOCK_VALUE,
                __UUID_CHARACTERISTIC_DEVICE_LOCK_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_SESSION_SERVICE_DEVICE_LOCK_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Session Records Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_SESSION_RECORDS_CHAR,
                HDLC_SESSION_SERVICE_SESSION_RECORDS_VALUE,
                __UUID_CHARACTERISTIC_SESSION_RECORDS_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: Session Records Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_SESSION_SERVICE_SESSION_RECORDS_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Session Status Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_SESSION_STATUS_CHAR,
                HDLC_SESSION_SERVICE_SESSION_STATUS_VALUE,
                __UUID_CHARACTERISTIC_SESSION_STATUS_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE  ),
            /* Descriptor: Session Status Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_SESSION_SERVICE_SESSION_STATUS_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: FINDMY DEVICE Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_FINDMY_DEVICE_CHAR,
                HDLC_SESSION_SERVICE_FINDMY_DEVICE_VALUE,
                __UUID_CHARACTERISTIC_FINDMY_DEVICE_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: FINDMY DEVICE Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_SESSION_SERVICE_FINDMY_DEVICE_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: SCREEN /LED Control  Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_SCREEN_LED_CONTROL_CHAR,
                HDLC_SESSION_SERVICE_SCREEN_LED_CONTROL_VALUE,
                __UUID_CHARACTERISTIC_SCREEN_LED_CONTROL_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
        /* Characteristic: Factory Reset  Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_FACTORY_RESET_CHAR,
                HDLC_SESSION_SERVICE_FACTORY_RESET_VALUE,
                __UUID_CHARACTERISTIC_FACTORY_RESET_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE  ),
        /* Characteristic: HEATING Profile Select Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_HEATING_PROF_SEL_CHAR,
                HDLC_SESSION_SERVICE_HEATING_PROF_SEL_VALUE,
                __UUID_CHARACTERISTIC_HEATING_PROF_SEL_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: HEATING Profile Select Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_SESSION_SERVICE_HEATING_PROF_SEL_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Haptic Set  Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_HAPTIC_SET_CHAR,
                HDLC_SESSION_SERVICE_HAPTIC_SET_VALUE,
                __UUID_CHARACTERISTIC_HAPTIC_SET_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ ,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
        /* Characteristic: Buzzer speaker set Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_SESSION_SERVICE_BUZZER_SPEAKER_SET_CHAR,
                HDLC_SESSION_SERVICE_BUZZER_SPEAKER_SET_VALUE,
                __UUID_CHARACTERISTIC_BUZZER_SPEAKER_SET_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ ,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
    /* Primary Service: Debug Service */
    PRIMARY_SERVICE_UUID128 (
            HDLS_DEBUG_SERVICE,
            __UUID_SERVICE_CUSTOM_DEBUG_SERVICE),
        /* Characteristic: Last Error Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_DEBUG_SERVICE_LAST_ERROR_CHAR,
                HDLC_DEBUG_SERVICE_LAST_ERROR_VALUE,
                __UUID_CHARACTERISTIC_LAST_ERROR_CHARACTERISTIC,
                GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: Last Error Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_DEBUG_SERVICE_LAST_ERROR_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Event Log Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_DEBUG_SERVICE_EVENT_LOG_CHAR,
                HDLC_DEBUG_SERVICE_EVENT_LOG_VALUE,
                __UUID_CHARACTERISTIC_EVENT_LOG_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: Event Log Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_DEBUG_SERVICE_EVENT_LOG_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Lifecycle Data Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_DEBUG_SERVICE_LIFECYCLE_DATA_CHAR,
                HDLC_DEBUG_SERVICE_LIFECYCLE_DATA_VALUE,
                __UUID_CHARACTERISTIC_LIFECYCLE_DATA_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: Lifecycle Data Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_DEBUG_SERVICE_LIFECYCLE_DATA_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
    /* Primary Service: Device Management Service */
    PRIMARY_SERVICE_UUID128 (
            HDLS_DEVICE_MANAGEMENT_SERVICE,
            __UUID_SERVICE_CUSTOM_DEVICE_MANAGEMENT_SERVICE),
        /* Characteristic: Version Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_DEVICE_MANAGEMENT_SERVICE_VERSION_CHAR,
                HDLC_DEVICE_MANAGEMENT_SERVICE_VERSION_VALUE,
                __UUID_CHARACTERISTIC_VERSION_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
        /* Characteristic: Control Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_DEVICE_MANAGEMENT_SERVICE_CONTROL_CHAR,
                HDLC_DEVICE_MANAGEMENT_SERVICE_CONTROL_VALUE,
                __UUID_CHARACTERISTIC_CONTROL_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: Control Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_DEVICE_MANAGEMENT_SERVICE_CONTROL_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
        /* Characteristic: Payload Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_DEVICE_MANAGEMENT_SERVICE_PAYLOAD_CHAR,
                HDLC_DEVICE_MANAGEMENT_SERVICE_PAYLOAD_VALUE,
                __UUID_CHARACTERISTIC_PAYLOAD_CHARACTERISTIC,
				GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_WRITE_NO_RESPONSE,
				GATTDB_PERM_WRITE_CMD | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
        /* Characteristic: Challenge Characteristic */
        CHARACTERISTIC_UUID128_WRITABLE (
                HDLC_DEVICE_MANAGEMENT_SERVICE_CHALLENGE_CHAR,
                HDLC_DEVICE_MANAGEMENT_SERVICE_CHALLENGE_VALUE,
                __UUID_CHARACTERISTIC_CHALLENGE_CHARACTERISTIC,
                GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE ),
            /* Descriptor: Challenge Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_DEVICE_MANAGEMENT_SERVICE_CHALLENGE_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_AUTH_WRITABLE),
    // /* Primary Service: Age Verification Service */
    // PRIMARY_SERVICE_UUID128 (
    //         HDLS_AGE_VERIFICATION_SERVICE,
    //         __UUID_SERVICE_CUSTOM_AGE_VERIFICATION_SERVICE),
    //     /* Characteristic: Age Challenge Characteristic */
    //     CHARACTERISTIC_UUID128_WRITABLE (
    //             HDLC_AGE_VERIFICATION_SERVICE_AGE_CHANLLENGE_GEN_CHAR,
    //             HDLC_AGE_VERIFICATION_SERVICE_AGE_CHANLLENGE_GEN_VALUE,
    //             __UUID_CHARACTERISTIC_AGE_CHANLLENGE_GEN_CHARACTERISTIC,
    //             GATTDB_CHAR_PROP_READ,
    //             GATTDB_PERM_WRITE_REQ | GATTDB_PERM_READABLE/*| GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE */),
    //     /* Characteristic: Age Verification Characteristic */
    //     CHARACTERISTIC_UUID128_WRITABLE (
    //             HDLC_AGE_VERIFICATION_SERVICE_AGE_SIGNATURE_VERF_CHAR,
    //             HDLC_AGE_VERIFICATION_SERVICE_AGE_SIGNATURE_VERF_VALUE,
    //             __UUID_CHARACTERISTIC_AGE_SIGNATURE_VERF_CHARACTERISTIC,
    //             GATTDB_CHAR_PROP_WRITE | GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
    //             GATTDB_PERM_WRITE_REQ | GATTDB_PERM_READABLE/*| GATTDB_PERM_AUTH_READABLE | GATTDB_PERM_WRITE_REQ | GATTDB_PERM_AUTH_WRITABLE */),
    //         /* Descriptor: AGE_SIGNATURE_VERF Client Characteristic Configuration */
    //         CHAR_DESCRIPTOR_UUID16_WRITABLE (
    //                 HDLD_AGE_VERIFICATION_SERVICE_AGE_SIGNATURE_VERF_CLIENT_CHAR_CONFIG,
    //                 __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
    //                 GATTDB_PERM_VARIABLE_LENGTH | GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);
// const uint8_t debug_service_event_log_sample_dat[15] = { 0xff, 0xff, 0xff, 0xff, 0xff,
//                                                          0xff, 0xff, 0xff, 0xff, 0xff,
//                                                          0xff, 0xff, 0xff, 0xff, 0xff,};

/******************************************************************************
* GATT Initial Value Arrays
******************************************************************************/
uint8_t app_gap_device_name[16] = {'A', 'd', 'o', 'n', 'i', 's', '1', 'P',};
uint8_t app_gap_appearance[] = {0x00, 0x00,};
uint8_t app_gatt_service_changed[] = {0x05, 0x00, 0x09, 0x00,};//Default: {0x01, 0x00, 0xff, 0xff,}; little-endian to big-endian
uint8_t app_gatt_service_changed_client_char_config[] = {0x00, 0x00,};
uint8_t app_bas_battery_level[] = {0x00,};
uint8_t app_bas_battery_level_char_presentation_format[] = {0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,};
uint8_t app_bas_battery_level_client_char_config[] = {0x00, 0x00,};

uint8_t app_ota_fw_upgrade_service_ota_upgrade_control_point[] = {'\0',};
uint8_t app_ota_fw_upgrade_service_ota_upgrade_control_point_client_char_config[] = {0x00, 0x00,};
uint8_t app_ota_fw_upgrade_service_ota_upgrade_data[] = {'\0',};

/******************************************************************************
* GATT Initial Value (Session Service Characterristic Value)
******************************************************************************/
session_service_device_information_char_read_t app_session_service_ext_device_information_char[] =
{
    {
        0x02,                                       //Firmware Major Version                         
        0x08,                                       //Firmware Minor Version                       
        0x0001,                                     //SW Revision (Patch)            
        0x0001,                                     //Board Classification         
        {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x4C, 0xE8, 0xAD, 0x54, 0xA2, 0xBD, 0xA5, 0xF2},//Serial Number
        0x01,                                       //Bootloader Version                            
    },
};

session_service_time_char_write_read_t app_session_service_ext_time_char[] =
{
    {                                                            
        0xFFFFFFFF,  //Used to read and set the current time on the device.                                                         
    },
};

session_service_battery_power_remaining_char_read_ntf_t app_session_service_ext_battery_power_remaining_char[] =
{
    {                                                            
        100,    //Will update every 1% and send it to the mobile app.
        0,      //0: Not Charging 1: Charging 2: Fast Charging 3:Wireless Charging
        10,     //The device shall provide the number of sessions expected from the remaining battery.
    },
};

session_service_device_lock_char_t app_session_service_ext_device_lock_char[] = 
{
    {                                                            
        0,    //0 = unlocked 1 =Locked
    },
};

session_service_records_char_t app_session_service_ext_records_char[] = 
{
    {  
        0x17B,         //Counter that increments each time a session is started on the device.
        0xFFFFFFFF,    //Epoch time of start of session.
        0xFFFF,        //Duration of the session in seconds.
        0xFFFF,          //Exit Codes from a session.
        0xFF,          //0 = Base Session1 = Session was run in “Boost Mode”.
        0xFF,			// heating profile
        0xFFFF,        //Max temperature that Z1 reached during the session.
//        0xFFFF,        //Max temperature that Z2 reached during the session.
        0xFFFF,        //Max temperature that the battery reached during the session
        0x00,          //0 = Trusted 1 = Untrusted
    },
};

session_service_status_char_t app_session_service_ext_status_char[] =
{
    {                                                            
        0,     //0 = Not In Session 1 =Ramp Up 2 = InSession 3 = EoS Warn
        0,     //0 = Standby 1 = Base 2 = Boost
        0,     // Eos Disable/Enable
        // 0,     // SelfClean Disable/Enable
    },
};

session_service_findmy_device_char_t app_session_service_ext_findmy_device_char[] = 
{
    {                                                            
        1,       //0 = Not Alerting 1 =Alerting                                              
        0x78,    //Total Seconds the alert should run for.
    },
};

session_service_screen_led_control_char_t app_session_service_ext_screen_led_control_char[] = 
{
    {                                                            
        100,     //% value relating to how bright the screen will appear to the user.
    },
};

session_service_factory_reset_char_t app_session_service_ext_factory_reset_char[] = 
{
    {                                                            
        0,     //When 1 is written to the characteristic the device will reset itself.
    },
};

session_service_heating_prof_sel_char_t app_session_service_ext_heating_prof_sel_char[] = 
{
    {
        0,     //0 = Request current profiles assigned to each mode. 1 = Request all heating profiles installed on the device. 2 = Request individual profile data. 3 = Set heating profile for a mode.                                              
        0,     //0 = Base 1 = Boost                                              
        0,     //Index number of the chosen profile to be used. 255 Is reserved for end of profile list.
    },
};

session_service_haptic_set_char_t app_session_service_ext_haptic_set_char[] = 
{
    {                                                            
        100,    //0 = Off 100 = FullPower
    },
};

session_service_buzzer_speaker_set_char_t app_session_service_ext_buzzer_speaker_set_char[] = 
{
    {
        100,    //0 = Off 100 = Maximum
    },
};

debug_service_last_error_char_t app_debug_service_ext_last_error_char[] = 
{
    {
//        0x64,//count
        0xFFFFFFFF,//timestamp
        0x0000,       //error code
    },
};


debug_service_event_log_char_t app_debug_service_ext_event_log_char[] = 
{
    {
        0x17B,            //count
        0xFFFFFFFF,       //time stamp
        0xFF,             //event code
        {0xFF, 0xFF, 0xFF, 0xFF, 0xFF,                //event data
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF,                //event data
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF},                //event data
    },
};

debug_service_lifecycle_data_char_t app_debug_service_ext_lifecycle_data_char[] = 
{
    {
        0xFF,      //opcode
        0x0,       //parameter
    },
};


/* Number of GATT initial value (Client Characteristic Configuration descriptor[0x2902]) arrays entries */
/**session service char config**/
uint8_t app_session_service_device_information_client_char_config[] = {0x00, 0x00,};
uint8_t app_session_service_battery_power_remaining_client_char_config[] = {0x00, 0x00,};
uint8_t app_session_service_device_lock_client_char_config[] = {0x00, 0x00,};
uint8_t app_session_service_session_records_client_char_config[] = {0x00, 0x00,};
uint8_t app_session_service_session_status_client_char_config[] = {0x00, 0x00,};
uint8_t app_session_service_findmy_device_client_char_config[] = {0x00, 0x00,};
uint8_t app_session_service_heating_prof_sel_client_char_config[] = {0x00, 0x00,};
/**debug service char config**/
uint8_t app_debug_service_last_error_char_config[] = {0x00, 0x00,};
uint8_t app_debug_service_event_log_char_config[] = {0x00, 0x00,};
uint8_t app_debug_service_lifecycle_data_char_config[] = {0x00, 0x00,};
/**device management service char config**/
uint8_t app_device_management_service_control_char_config[] = {0x00, 0x00,};
uint8_t app_device_management_service_challenge_char_config[] = {0x00, 0x00,};


/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = (sizeof(app_gap_device_name));
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_gatt_service_changed_len = (sizeof(app_gatt_service_changed));
const uint16_t app_gatt_service_changed_client_char_config_len =
    (sizeof(app_gatt_service_changed_client_char_config));
const uint16_t app_bas_battery_level_len = (sizeof(app_bas_battery_level));
const uint16_t app_bas_battery_level_char_presentation_format_len =
    (sizeof(app_bas_battery_level_char_presentation_format));
const uint16_t app_bas_battery_level_client_char_config_len =
    (sizeof(app_bas_battery_level_client_char_config));
//Number of OTA firmware upgrade service
const uint16_t app_ota_fw_upgrade_service_ota_upgrade_control_point_len =
    (sizeof(app_ota_fw_upgrade_service_ota_upgrade_control_point));
const uint16_t app_ota_fw_upgrade_service_ota_upgrade_control_point_client_char_config_len =
    (sizeof(app_ota_fw_upgrade_service_ota_upgrade_control_point_client_char_config));
const uint16_t app_ota_fw_upgrade_service_ota_upgrade_data_len =
    (sizeof(app_ota_fw_upgrade_service_ota_upgrade_data));
//Number of Session service characteristic
const uint16_t app_session_service_ext_device_information_char_len =
    (sizeof(session_service_device_information_char_read_t));
// const uint16_t app_session_service_device_information_client_char_config_len =
//     (sizeof(app_session_service_device_information_client_char_config));
const uint16_t app_session_service_ext_time_char_len =
    (sizeof(session_service_time_char_write_read_t));
const uint16_t app_session_service_ext_battery_power_remaining_char_len =
    (sizeof(session_service_battery_power_remaining_char_read_ntf_t));
const uint16_t app_session_service_ext_device_lock_char_len =
    (sizeof(session_service_device_lock_char_t));
const uint16_t app_session_service_ext_records_char_len =
    (sizeof(session_service_records_char_t));
const uint16_t app_session_service_ext_status_char_len =
    (sizeof(session_service_status_char_t));
const uint16_t app_session_service_ext_findmy_device_char_len =
    (sizeof(session_service_findmy_device_char_t));
const uint16_t app_session_service_ext_screen_led_control_char_len =
    (sizeof(session_service_screen_led_control_char_t));
//session service factory reset char not readable.
const uint16_t app_session_service_ext_heating_prof_sel_char_len =
    (sizeof(session_service_heating_prof_sel_char_t));
const uint16_t app_session_service_ext_haptic_set_char_len =
    (sizeof(session_service_haptic_set_char_t));
const uint16_t app_session_service_ext_buzzer_speaker_set_char_len =
    (sizeof(session_service_buzzer_speaker_set_char_t));

/**debug service char config**/
const uint16_t app_debug_service_ext_last_error_char_len =
    (sizeof(debug_service_last_error_char_t));
const uint16_t app_debug_service_ext_event_log_char_len =
    (sizeof(app_debug_service_ext_event_log_char[0]));
const uint16_t app_debug_service_ext_lifecycle_data_char_len =
    (sizeof(debug_service_lifecycle_data_char_t));


/******************************************************************************
* GATT database Lookup Table
******************************************************************************/
gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    {
        HDLC_GAP_DEVICE_NAME_VALUE,                                               /* attribute handle */
        MAX_LEN_GAP_DEVICE_NAME,                                                  /* maxlen */
        app_gap_device_name_len,                                                  /* curlen */
        app_gap_device_name,                                                      /* attribute data */
    },
    {
        HDLC_GAP_APPEARANCE_VALUE,                                                /* attribute handle */
        MAX_LEN_GAP_APPEARANCE,                                                   /* maxlen */
        app_gap_appearance_len,                                                   /* curlen */
        app_gap_appearance,                                                       /* attribute data */
    },
    {
        HDLC_GATT_SERVICE_CHANGED_VALUE,              /* attribute handle */
        MAX_LEN_GATT_SERVICE_CHANGED,                 /* maxlen */
        4,                                            /* curlen */
        app_gatt_service_changed,                     /* attribute data */
    },
    {
        HDLD_GATT_SERVICE_CHANGED_CLIENT_CHAR_CONFIG, /* attribute handle */
        MAX_LEN_GATT_SERVICE_CHANGED_CLIENT_CHAR_CONFIG,/* maxlen */
        2,                                            /* curlen */
        app_gatt_service_changed_client_char_config,  /* attribute data */
    },
    // {
    //     HDLC_BAS_BATTERY_LEVEL_VALUE,                                             /* attribute handle */
    //     MAX_LEN_BAS_BATTERY_LEVEL,                                                /* maxlen */
    //     app_bas_battery_level_len,                                                /* curlen */
    //     app_bas_battery_level,                                                    /* attribute data */
    // },
    // {
    //     HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT,                          /* attribute handle */
    //     MAX_LEN_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT,                       /* maxlen */
    //     app_bas_battery_level_char_presentation_format_len,                       /* curlen */
    //     app_bas_battery_level_char_presentation_format,                           /* attribute data */
    // },
    // {
    //     HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,                                /* attribute handle */
    //     MAX_LEN_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,                             /* maxlen */
    //     2,                                                                        /* curlen */
    //     app_bas_battery_level_client_char_config,                                 /* attribute data */
    // },
    {
        HDLC_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_CONTROL_POINT_VALUE,              /* attribute handle */
        MAX_LEN_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_CONTROL_POINT,                 /* maxlen */
        app_ota_fw_upgrade_service_ota_upgrade_control_point_len,                 /* curlen */
        app_ota_fw_upgrade_service_ota_upgrade_control_point,                     /* attribute data */
    },
    {
        HDLD_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_CONTROL_POINT_CLIENT_CHAR_CONFIG, /* attribute handle */
        MAX_LEN_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_CONTROL_POINT_CLIENT_CHAR_CONFIG,/* maxlen */
        2,                                                                        /* curlen */
        app_ota_fw_upgrade_service_ota_upgrade_control_point_client_char_config,  /* attribute data */
    },
    {
        HDLC_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_DATA_VALUE,                       /* attribute handle */
        MAX_LEN_OTA_FW_UPGRADE_SERVICE_OTA_UPGRADE_DATA,                          /* maxlen */
        app_ota_fw_upgrade_service_ota_upgrade_data_len,                          /* curlen */
        app_ota_fw_upgrade_service_ota_upgrade_data,                              /* attribute data */
    },
    {
        HDLC_SESSION_SERVICE_DEVICE_INFORMATION_VALUE,                            /* attribute handle */
        MAX_LEN_SESSION_SERVICE_DEVICE_INFORMATION_CHARACTERISTIC,                /* maxlen */
        app_session_service_ext_device_information_char_len,                      /* curlen */
		(uint8_t *)app_session_service_ext_device_information_char,               /* attribute data */
    },
    {
        HDLD_SESSION_SERVICE_DEVICE_INFORMATION_CLIENT_CHAR_CONFIG,               /* attribute handle */
        MAX_LEN_SESSION_SERVICE_DEVICE_INFORMATION_CLIENT_CHAR_CONFIG,            /* maxlen */
        2,                                                                        /* curlen */
        app_session_service_device_information_client_char_config,                /* attribute data */
    },
    {
        HDLC_SESSION_SERVICE_TIME_VALUE,                                          /* attribute handle */
        MAX_LEN_SESSION_SERVICE_TIME_CHARACTERISTIC,                              /* maxlen */
        app_session_service_ext_time_char_len,                                    /* curlen */
		(uint8_t *)app_session_service_ext_time_char,                             /* attribute data */
    },
    {
        HDLC_SESSION_SERVICE_BATTERY_POWER_REMAINING_VALUE,                       /* attribute handle */
        MAX_LEN_SESSION_SERVICE_BATTERY_POWER_REMAINING_CHARACTERISTIC,           /* maxlen */
        app_session_service_ext_battery_power_remaining_char_len,                 /* curlen */
		(uint8_t *)app_session_service_ext_battery_power_remaining_char,          /* attribute data */
    },
    {
        HDLD_SESSION_SERVICE_BATTERY_POWER_REMAINING_CLIENT_CHAR_CONFIG,          /* attribute handle */
        MAX_LEN_SESSION_SERVICE_BATTERY_POWER_REMAINING_CLIENT_CHAR_CONFIG,       /* maxlen */
        2,                                                                        /* curlen */
        app_session_service_battery_power_remaining_client_char_config,           /* attribute data */
    },
    {
        HDLC_SESSION_SERVICE_DEVICE_LOCK_VALUE,                                   /* attribute handle */
        MAX_LEN_SESSION_SERVICE_DEVICE_LOCK_CHARACTERISTIC,                       /* maxlen */
        app_session_service_ext_device_lock_char_len,                             /* curlen */
		(uint8_t *)app_session_service_ext_device_lock_char,                      /* attribute data */
    },
    {
        HDLD_SESSION_SERVICE_DEVICE_LOCK_CLIENT_CHAR_CONFIG,                      /* attribute handle */
        MAX_LEN_SESSION_SERVICE_DEVICE_LOCK_CLIENT_CHAR_CONFIG,                   /* maxlen */
        2,                                                                        /* curlen */
        app_session_service_device_lock_client_char_config,                       /* attribute data */
    },
    {
        HDLC_SESSION_SERVICE_SESSION_RECORDS_VALUE,                               /* attribute handle */
        MAX_LEN_SESSION_SERVICE_SESSION_RECORDS_CHARACTERISTIC,                   /* maxlen */
        app_session_service_ext_records_char_len,                                 /* curlen */
		(uint8_t *)app_session_service_ext_records_char,                          /* attribute data */
    },
    {
        HDLD_SESSION_SERVICE_SESSION_RECORDS_CLIENT_CHAR_CONFIG,                  /* attribute handle */
        MAX_LEN_SESSION_SERVICE_SESSION_RECORDS_CLIENT_CHAR_CONFIG,               /* maxlen */
        2,                                                                        /* curlen */
        app_session_service_session_records_client_char_config,                   /* attribute data */
    },
    {
        HDLC_SESSION_SERVICE_SESSION_STATUS_VALUE,                                /* attribute handle */
        MAX_LEN_SESSION_SERVICE_SESSION_STATUS_CHARACTERISTIC,                    /* maxlen */
        app_session_service_ext_status_char_len,                                  /* curlen */
		(uint8_t *)app_session_service_ext_status_char,                           /* attribute data */
    },
    {
        HDLD_SESSION_SERVICE_SESSION_STATUS_CLIENT_CHAR_CONFIG,                   /* attribute handle */
        MAX_LEN_SESSION_SERVICE_SESSION_STATUS_CLIENT_CHAR_CONFIG,                /* maxlen */
        2,                                                                        /* curlen */
        app_session_service_session_status_client_char_config,                    /* attribute data */
    },
    {
        HDLC_SESSION_SERVICE_FINDMY_DEVICE_VALUE,                                 /* attribute handle */
        MAX_LEN_SESSION_SERVICE_FINDMY_DEVICE_CHARACTERISTIC,                     /* maxlen */
        app_session_service_ext_findmy_device_char_len,                           /* curlen */
		(uint8_t *)app_session_service_ext_findmy_device_char,                    /* attribute data */
    }, 
    {
        HDLD_SESSION_SERVICE_FINDMY_DEVICE_CLIENT_CHAR_CONFIG,                    /* attribute handle */
        MAX_LEN_SESSION_SERVICE_FINDMY_DEVICE_CLIENT_CHAR_CONFIG,                 /* maxlen */
        2,                                                                        /* curlen */
        app_session_service_findmy_device_client_char_config,                     /* attribute data */
    },
    { 
        HDLC_SESSION_SERVICE_SCREEN_LED_CONTROL_VALUE,                            /* attribute handle */
        MAX_LEN_SESSION_SERVICE_SCREEN_LED_CONTROL_CHARACTERISTIC,                /* maxlen */
        app_session_service_ext_screen_led_control_char_len,                      /* curlen */
		(uint8_t *)app_session_service_ext_screen_led_control_char,               /* attribute data */
    },
    { 
        HDLC_SESSION_SERVICE_HEATING_PROF_SEL_VALUE,                              /* attribute handle */
        MAX_LEN_SESSION_SERVICE_HEATING_PROF_SEL_CHARACTERISTIC,                  /* maxlen */
        app_session_service_ext_heating_prof_sel_char_len,                        /* curlen */
		(uint8_t *)app_session_service_ext_heating_prof_sel_char,                 /* attribute data */
    }, 
    {
        HDLD_SESSION_SERVICE_HEATING_PROF_SEL_CLIENT_CHAR_CONFIG,                 /* attribute handle */
        MAX_LEN_SESSION_SERVICE_HEATING_PROF_SEL_CLIENT_CHAR_CONFIG,              /* maxlen */
        2,                                                                        /* curlen */
        app_session_service_heating_prof_sel_client_char_config,                  /* attribute data */
    },
    { 
        HDLC_SESSION_SERVICE_HAPTIC_SET_VALUE,                                    /* attribute handle */
        MAX_LEN_SESSION_SERVICE_HAPTIC_SET_CHARACTERISTIC,                        /* maxlen */
        app_session_service_ext_haptic_set_char_len,                              /* curlen */
		(uint8_t *)app_session_service_ext_haptic_set_char,                       /* attribute data */
    },
    { 
        HDLC_SESSION_SERVICE_BUZZER_SPEAKER_SET_VALUE,                            /* attribute handle */
        MAX_LEN_SESSION_SERVICE_BUZZER_SPEAKER_SET_CHARACTERISTIC,                /* maxlen */
        app_session_service_ext_buzzer_speaker_set_char_len,                      /* curlen */
        (uint8_t *)app_session_service_ext_buzzer_speaker_set_char,               /* attribute data */
    },
    { 
        HDLC_DEBUG_SERVICE_LAST_ERROR_VALUE,                                      /* attribute handle */
        MAX_LEN_DEBUG_SERVICE_LAST_ERROR_CHARACTERISTIC,                          /* maxlen */
        app_debug_service_ext_last_error_char_len,                                /* curlen */
		(uint8_t *)app_debug_service_ext_last_error_char,                         /* attribute data */
    }, 
    {
        HDLD_DEBUG_SERVICE_LAST_ERROR_CLIENT_CHAR_CONFIG,                         /* attribute handle */
        MAX_LEN_DEBUG_SERVICE_LAST_ERROR_CLIENT_CHAR_CONFIG,                      /* maxlen */
        2,                                                                        /* curlen */
        app_debug_service_last_error_char_config,                                 /* attribute data */
    },
    { 
        HDLC_DEBUG_SERVICE_EVENT_LOG_VALUE,                                       /* attribute handle */
        MAX_LEN_DEBUG_SERVICE_EVENT_LOG_CHARACTERISTIC,                           /* maxlen */
        app_debug_service_ext_event_log_char_len,                                 /* curlen */
		(uint8_t *)app_debug_service_ext_event_log_char,                          /* attribute data */
    },  
    { 
        HDLD_DEBUG_SERVICE_EVENT_LOG_CLIENT_CHAR_CONFIG,                          /* attribute handle */
        MAX_LEN_DEBUG_SERVICE_EVENT_LOG_CLIENT_CHAR_CONFIG,                       /* maxlen */
        2,                                                                        /* curlen */
        app_debug_service_event_log_char_config,                                  /* attribute data */
    },
    { 
        HDLC_DEBUG_SERVICE_LIFECYCLE_DATA_VALUE,                                  /* attribute handle */
        MAX_LEN_DEBUG_SERVICE_LIFECYCLE_DATA_CHARACTERISTIC,                      /* maxlen */
        app_debug_service_ext_lifecycle_data_char_len,                            /* curlen */
		(uint8_t *)app_debug_service_ext_lifecycle_data_char,                     /* attribute data */
    }, 
    {
        HDLD_DEBUG_SERVICE_LIFECYCLE_DATA_CLIENT_CHAR_CONFIG,                     /* attribute handle */
        MAX_LEN_DEBUG_SERVICE_LIFECYCLE_DATA_CLIENT_CHAR_CONFIG,                  /* maxlen */
        2,                                                                        /* curlen */
        app_debug_service_lifecycle_data_char_config,                             /* attribute data */
    },
    {
        HDLD_DEVICE_MANAGEMENT_SERVICE_CONTROL_CLIENT_CHAR_CONFIG,                /* attribute handle */
        MAX_LEN_DEVICE_MANAGEMENT_SERVICE_CONTROL_CLIENT_CHAR_CONFIG,             /* maxlen */
        2,                                                                        /* curlen */
        app_device_management_service_control_char_config,                        /* attribute data */
    },
    {
        HDLD_DEVICE_MANAGEMENT_SERVICE_CHALLENGE_CLIENT_CHAR_CONFIG,              /* attribute handle */
        MAX_LEN_DEVICE_MANAGEMENT_SERVICE_CHALLENGE_CLIENT_CHAR_CONFIG,           /* maxlen */
        2,                                                                        /* curlen */
        app_device_management_service_challenge_char_config,                      /* attribute data */
    },
};


/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size =
    (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/*
    补充其他buf len?
**/



