/***************************************************************************//**
* File Name: cycfg_gap.c
*
* Description:
* BLE device's GAP configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.90.0.2529
*
********************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gap.h"

/* Device address */
wiced_bt_device_address_t cy_bt_device_address = {0x00, 0xA0, 0x50, 0x00, 0x00, 0x00};
wiced_bt_device_address_t cy_bt_remote_address = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

const uint8_t cy_bt_adv_packet_elem_0[1] = { 0x06 };
const uint8_t cy_bt_adv_packet_elem_1[16] = { 0x49, 0x34, 0x68, 0x40, 0x97, 0x1B, /**/0x0A, 0x00, 0x05, /**/0x02, 0x78, 0xE3, 0xB5, 0xC8, 0xD6, 0x6C };
// const uint8_t cy_bt_adv_packet_elem_1[16] = { 0x6C, 0xD6, 0xC8, 0xB5, 0xE3, 0x78, 0x02, 0x05, 0x00, 0x0A, 0x1B, 0x97, 0x40, 0x68, 0x34, 0x49 };

const uint8_t cy_bt_scan_rsp_packet_elem_0[9] = { 0x41, 0x64, 0x6F, 0x6E, 0x69, 0x73, 0x20, 0x31, 0x50 };
                                                //Manf. ID (2 bytes) + MAC Address(6 bytes) + Device Color (1 byte) + Device Type (1 byte)
const uint8_t cy_bt_scan_rsp_packet_elem_1[10] = { 0xff, 0xff, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0xff, 0xff};


#pragma pack(1)
wiced_bt_ble_advert_elem_t cy_bt_adv_packet_data[2] = /* legacy adv format 31 bytes*/
{
    /* Flags */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_FLAG, 
        .len = 1, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_0, //02 01 06(BLE type) 
    },
    /* 128 bit UUIDs complete */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_128SRV_COMPLETE, 
        .len = 16, 
        .p_data = (uint8_t*)cy_bt_adv_packet_elem_1, //17 07 "session service 000a uuid"
    },
};

wiced_bt_ble_advert_elem_t cy_bt_scan_rsp_packet_data[2] = /* legacy scan_response format 31 bytes*/
{
    /* Complete local name */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_NAME_COMPLETE, 
        .len = 9, 
        .p_data = (uint8_t*)cy_bt_scan_rsp_packet_elem_0, //A 09 "Adonis 1P"
    },
    /* manufacturer data  */
    {
        .advert_type = BTM_BLE_ADVERT_TYPE_MANUFACTURER, 
        .len = 10, 
        .p_data = (uint8_t*)cy_bt_scan_rsp_packet_elem_1, //
    },
};
#pragma pack()
